
<div class="row">
    <div class="span12">
        <h2>Form Tests</h2>

        <?php
        // Init Form
        $form = $this->form;
        $form->prepare();
        ?>
        <?php echo $this->form()->openTag($form); ?>

            <div class="control-group">
                <?php $elem = $form->get('multicb'); ?>
                <label>Multi Checkbox:</label>
                <?php echo $this->formMultiCheckbox($elem); ?>
                <?php echo $this->formElementErrors($elem); ?>
            </div>

            <div class="control-group">
                <?php $elem = $form->get('radio'); ?>
                <label>Radio:</label>
                <?php echo $this->formRadio($elem); ?>
                <?php echo $this->formElementErrors($elem); ?>
            </div>

            <button class="btn btn-primary">Submit</button>

        <?php echo $this->form()->closeTag($form); ?>

        <?php
        if (!empty($this->data)) {
            ?><h3>Postback</h3>
            <pre><?php
            print_r($this->data);
            ?></pre><?php
        }
        ?>
    </div>
</div>
